### ISSUE TITLE
Proliferation of Group classes

### ISSUE THREAD

**Issue by endgame** [cmk/magmas#1]
Groups turn out to be a useful structure in Haskell, and I've seen them in a number of other packages (`groups`, and reinvented again inside `patch`).

As people become more aware of them, it will be frustrating if there's a proliferation of similar-but-incompatible `Group` classes with different instances on different types. Is there a way to depend on `groups` to get what you need?

**Comment by endgame** [comment]
Also [`group-theory`](https://hackage.haskell.org/package/group-theory) was recently released.

**Comment by cmk** [comment]
Looks promising.

At the time I wrote this I needed loops and magmas, which are non-monoidal
objects weaker than groups <https://en.wikipedia.org/wiki/Magma_(algebra)>.
One very unfortunate aspect of the Haskell type class system is the
inability to easily introduce upper dependencies to a pre-existing class.
Your pet peeve is thus fairly endemic to the ecosystem. I'd suggest voting
with your own upstream dependency selections rather than attempting to
police the matter.
